const fs = require('fs');
const path = require('path');

const newProducts = `const productsData = [
    // --- ANNIVERSARY ---
    {
      name: 'Luxury Strawberry Tower',
      slug: 'luxury-strawberry-tower',
      description: 'A stunning tower of fresh strawberries dipped in premium Belgian chocolate, decorated with edible flowers and gold flakes. Perfect for anniversaries or special events.',
      price: 150,
      stock: 10,
      categoryId: categories['anniversary'],
      isFeatured: true,
      tags: ['edible arrangement', 'strawberry', 'chocolate', 'luxury'],
      images: ['/products/prod-1.jpg'],
    },
    {
      name: 'Golden Heart Chocolate Box',
      slug: 'golden-heart-chocolate-box',
      description: 'A heart-shaped box filled with golden-wrapped artisan chocolates.',
      price: 45,
      stock: 15,
      categoryId: categories['anniversary'],
      isFeatured: false,
      tags: ['chocolate', 'heart', 'anniversary'],
      images: ['/products/prod-3.jpg'],
    },
    {
      name: 'Rose & Berry Elegance',
      slug: 'rose-berry-elegance',
      description: 'An elegant mix of fresh red roses and chocolate-dipped strawberries in a sleek black box.',
      price: 120,
      stock: 12,
      categoryId: categories['anniversary'],
      isFeatured: true,
      tags: ['roses', 'strawberries', 'anniversary'],
      images: ['/products/prod-2.jpg'],
    },
    {
      name: 'Eternal Love Bouquet',
      slug: 'eternal-love-bouquet',
      description: 'A grand bouquet of 50 premium red roses.',
      price: 200,
      stock: 5,
      categoryId: categories['anniversary'],
      isFeatured: false,
      tags: ['roses', 'bouquet', 'anniversary'],
      images: ['/products/prod-4.jpg'],
    },
    {
      name: 'Anniversary Sweet Platter',
      slug: 'anniversary-sweet-platter',
      description: 'A platter of various sweet treats perfect for sharing on a special day.',
      price: 85,
      stock: 20,
      categoryId: categories['anniversary'],
      isFeatured: false,
      tags: ['sweets', 'platter', 'anniversary'],
      images: ['/products/prod-5.jpg'],
    },

    // --- CUSTOM GIFTS ---
    {
      name: 'Custom Alphabet Floral Box',
      slug: 'custom-alphabet-floral-box',
      description: 'Beautiful fresh roses arranged in the shape of a letter of your choice, presented in our signature acrylic box.',
      price: 85,
      stock: 20,
      categoryId: categories['custom-gifts'],
      isFeatured: true,
      tags: ['flowers', 'roses', 'custom'],
      images: ['/products/prod-2.jpg'],
    },
    {
      name: 'Personalized Engraved Mug',
      slug: 'personalized-engraved-mug',
      description: 'A high-quality ceramic mug with personalized engraving.',
      price: 25,
      stock: 50,
      categoryId: categories['custom-gifts'],
      isFeatured: false,
      tags: ['mug', 'custom'],
      images: ['/products/prod-5.jpg'],
    },
    {
      name: 'Custom Chocolate Message',
      slug: 'custom-chocolate-message',
      description: 'Say it with chocolate! A box of chocolates spelling out a custom message.',
      price: 55,
      stock: 30,
      categoryId: categories['custom-gifts'],
      isFeatured: true,
      tags: ['chocolate', 'custom', 'message'],
      images: ['/products/prod-1.jpg'],
    },
    {
      name: 'Design-Your-Own Fruit Basket',
      slug: 'design-your-own-fruit-basket',
      description: 'Select your favorite fruits and chocolate dips to create the perfect custom basket.',
      price: 110,
      stock: 15,
      categoryId: categories['custom-gifts'],
      isFeatured: false,
      tags: ['fruit', 'basket', 'custom'],
      images: ['/products/prod-6.jpg'],
    },
    {
      name: 'Bespoke Gift Hamper',
      slug: 'bespoke-gift-hamper',
      description: 'Work with our team to create a completely custom hamper from our premium selection.',
      price: 150,
      stock: 10,
      categoryId: categories['custom-gifts'],
      isFeatured: false,
      tags: ['hamper', 'custom', 'bespoke'],
      images: ['/products/prod-3.jpg'],
    },

    // --- BIRTHDAY GIFTS ---
    {
      name: 'Classic Birthday Hamper',
      slug: 'classic-birthday-hamper',
      description: 'A delightful basket featuring imported chocolates, a customized mug, a scented candle, and a handwritten birthday card.',
      price: 60,
      comparePrice: 75,
      stock: 15,
      categoryId: categories['birthday-gifts'],
      isFeatured: false,
      tags: ['hamper', 'birthday', 'chocolates'],
      images: ['/products/prod-3.jpg'],
    },
    {
      name: 'Birthday Balloon & Berry Combo',
      slug: 'birthday-balloon-berry-combo',
      description: 'A festive helium balloon paired with a box of colorful chocolate-dipped strawberries.',
      price: 45,
      stock: 25,
      categoryId: categories['birthday-gifts'],
      isFeatured: true,
      tags: ['birthday', 'balloon', 'berries'],
      images: ['/products/prod-1.jpg'],
    },
    {
      name: 'Ultimate Birthday Cake Box',
      slug: 'ultimate-birthday-cake-box',
      description: 'A decadent mini birthday cake surrounded by fresh berries and macarons.',
      price: 90,
      stock: 8,
      categoryId: categories['birthday-gifts'],
      isFeatured: false,
      tags: ['birthday', 'cake', 'macarons'],
      images: ['/products/prod-4.jpg'],
    },
    {
      name: 'Surprise Party Platter',
      slug: 'surprise-party-platter',
      description: 'A large platter of mixed fruits, chocolates, and cookies designed for a birthday party.',
      price: 130,
      stock: 12,
      categoryId: categories['birthday-gifts'],
      isFeatured: true,
      tags: ['birthday', 'party', 'platter'],
      images: ['/products/prod-6.jpg'],
    },
    {
      name: 'Birthday Bliss Box',
      slug: 'birthday-bliss-box',
      description: 'A curated box of self-care items and sweet treats for a relaxing birthday.',
      price: 75,
      stock: 20,
      categoryId: categories['birthday-gifts'],
      isFeatured: false,
      tags: ['birthday', 'self-care', 'box'],
      images: ['/products/prod-2.jpg'],
    },

    // --- EID SPECIAL ---
    {
      name: 'Premium Eid Date & Nut Platter',
      slug: 'premium-eid-date-nut-platter',
      description: 'A luxurious wooden platter filled with premium stuffed Ajwa dates, roasted nuts, and Turkish delights.',
      price: 120,
      stock: 50,
      categoryId: categories['eid-special'],
      isFeatured: true,
      tags: ['eid', 'dates', 'nuts', 'platter'],
      images: ['/products/prod-4.jpg'],
    },
    {
      name: 'Eid Crescent Floral Arrangement',
      slug: 'eid-crescent-floral-arrangement',
      description: 'A beautiful crescent moon-shaped arrangement of white and gold flowers.',
      price: 85,
      stock: 15,
      categoryId: categories['eid-special'],
      isFeatured: false,
      tags: ['eid', 'floral', 'crescent'],
      images: ['/products/prod-2.jpg'],
    },
    {
      name: 'Family Eid Treat Box',
      slug: 'family-eid-treat-box',
      description: 'A large box of assorted chocolates, dates, and sweets perfect for family gatherings.',
      price: 95,
      stock: 30,
      categoryId: categories['eid-special'],
      isFeatured: true,
      tags: ['eid', 'family', 'treats'],
      images: ['/products/prod-3.jpg'],
    },
    {
      name: 'Luxury Eid Gift Set',
      slug: 'luxury-eid-gift-set',
      description: 'A premium gift set including artisanal perfumes, stuffed dates, and gold-dusted chocolates.',
      price: 250,
      stock: 5,
      categoryId: categories['eid-special'],
      isFeatured: false,
      tags: ['eid', 'luxury', 'gift set'],
      images: ['/products/prod-5.jpg'],
    },
    {
      name: 'Sweet Eid Greetings Basket',
      slug: 'sweet-eid-greetings-basket',
      description: 'A welcoming basket filled with traditional Eid sweets and fresh fruit.',
      price: 65,
      stock: 40,
      categoryId: categories['eid-special'],
      isFeatured: false,
      tags: ['eid', 'basket', 'sweets'],
      images: ['/products/prod-6.jpg'],
    },

    // --- CORPORATE ---
    {
      name: 'Corporate Executive Box',
      slug: 'corporate-executive-box',
      description: 'A sleek black gift box containing a premium leather wallet, a customized pen, and artisan chocolates. Ideal for client appreciation.',
      price: 95,
      stock: 100,
      categoryId: categories['corporate'],
      isFeatured: false,
      tags: ['corporate', 'leather', 'executive'],
      images: ['/products/prod-5.jpg'],
    },
    {
      name: 'Client Appreciation Fruit Basket',
      slug: 'client-appreciation-fruit-basket',
      description: 'A professional and elegant fruit basket to show appreciation to your top clients.',
      price: 110,
      stock: 50,
      categoryId: categories['corporate'],
      isFeatured: true,
      tags: ['corporate', 'client', 'fruit basket'],
      images: ['/products/prod-6.jpg'],
    },
    {
      name: 'Team Celebration Platter',
      slug: 'team-celebration-platter',
      description: 'A massive platter of assorted treats perfect for office parties and team celebrations.',
      price: 180,
      stock: 20,
      categoryId: categories['corporate'],
      isFeatured: false,
      tags: ['corporate', 'team', 'platter'],
      images: ['/products/prod-4.jpg'],
    },
    {
      name: 'Branded Chocolate Box',
      slug: 'branded-chocolate-box',
      description: 'A box of premium chocolates featuring your company logo on the packaging.',
      price: 45,
      stock: 200,
      categoryId: categories['corporate'],
      isFeatured: true,
      tags: ['corporate', 'branded', 'chocolate'],
      images: ['/products/prod-1.jpg'],
    },
    {
      name: 'Welcome Onboard Kit',
      slug: 'welcome-onboard-kit',
      description: 'A thoughtful kit for new employees, including a mug, notebook, and gourmet snacks.',
      price: 55,
      stock: 150,
      categoryId: categories['corporate'],
      isFeatured: false,
      tags: ['corporate', 'onboarding', 'kit'],
      images: ['/products/prod-3.jpg'],
    },

    // --- THANK YOU ---
    {
      name: 'Gourmet Fruit & Chocolate Bouquet',
      slug: 'gourmet-fruit-chocolate-bouquet',
      description: 'Our signature edible arrangement featuring fresh pineapples shaped like daisies, chocolate-dipped apples, and fresh grapes.',
      price: 78,
      stock: 25,
      categoryId: categories['thank-you'],
      isFeatured: true,
      tags: ['edible arrangement', 'fruits', 'thank you'],
      images: ['/products/prod-6.jpg'],
    },
    {
      name: 'Simple Thanks Fruit Box',
      slug: 'simple-thanks-fruit-box',
      description: 'A simple yet elegant box of fresh seasonal fruits to say a quick thank you.',
      price: 35,
      stock: 40,
      categoryId: categories['thank-you'],
      isFeatured: false,
      tags: ['thank you', 'fruit', 'box'],
      images: ['/products/prod-3.jpg'],
    },
    {
      name: 'Gratitude Chocolate Assortment',
      slug: 'gratitude-chocolate-assortment',
      description: 'A beautiful assortment of artisan chocolates with a "Thank You" card.',
      price: 50,
      stock: 30,
      categoryId: categories['thank-you'],
      isFeatured: true,
      tags: ['thank you', 'chocolate'],
      images: ['/products/prod-1.jpg'],
    },
    {
      name: 'Appreciation Floral Mini',
      slug: 'appreciation-floral-mini',
      description: 'A small, bright floral arrangement perfect for a desk or side table.',
      price: 45,
      stock: 25,
      categoryId: categories['thank-you'],
      isFeatured: false,
      tags: ['thank you', 'floral', 'mini'],
      images: ['/products/prod-2.jpg'],
    },
    {
      name: 'Mega Thanks Hamper',
      slug: 'mega-thanks-hamper',
      description: 'A massive hamper filled with fruits, chocolates, and wine to show immense gratitude.',
      price: 160,
      stock: 10,
      categoryId: categories['thank-you'],
      isFeatured: false,
      tags: ['thank you', 'hamper', 'mega'],
      images: ['/products/prod-5.jpg'],
    }
  ];`;

const filePath = path.join(__dirname, 'seed.js');
let content = fs.readFileSync(filePath, 'utf8');

// Replace the existing productsData array
const regex = /const productsData = \[[\s\S]*?\];/;
content = content.replace(regex, newProducts);

fs.writeFileSync(filePath, content);
console.log('Seed file updated successfully.');
