const logger = require('../config/logger');
const ApiError = require('../utils/apiError');

/**
 * Get Clover Base URL based on environment variable (Sandbox vs Live Production)
 */
const getCloverBaseUrl = () => {
  const env = (process.env.CLOVER_ENVIRONMENT || 'sandbox').toLowerCase();
  return env === 'production'
    ? 'https://scl.clover.com'
    : 'https://scl-sandbox.dev.clover.com';
};

/**
 * Get private Clover API Access Token from environment
 */
const getCloverAccessToken = () => {
  const token = process.env.CLOVER_ACCESS_TOKEN;
  if (!token) {
    throw ApiError.internal('CLOVER_ACCESS_TOKEN is not configured in server environment variables.');
  }
  return token;
};

/**
 * Execute a card charge on Clover using the single-use token generated by clover.js iframe
 *
 * @param {Object} params
 * @param {number} params.amountInCents - Amount in smallest currency unit (e.g., 2500 for $25.00 CAD)
 * @param {string} params.currency - 3-letter currency code (e.g., 'cad')
 * @param {string} params.sourceToken - Token returned by clover.js (clv_...)
 * @param {string} params.idempotencyKey - Unique key to guarantee safe retries and prevent double charges
 * @param {string} [params.orderNumber] - Store order reference number
 * @param {string} [params.clientIp] - Client IP for fraud detection
 * @returns {Promise<Object>} Clover charge response
 */
const createCharge = async ({
  amountInCents,
  currency = process.env.PAYMENT_CURRENCY || 'cad',
  sourceToken,
  idempotencyKey,
  orderNumber,
  clientIp,
}) => {
  const accessToken = getCloverAccessToken();
  const baseUrl = getCloverBaseUrl();

  if (!sourceToken) {
    throw ApiError.badRequest('Clover payment token (source) is required');
  }

  if (!idempotencyKey) {
    throw ApiError.badRequest('Idempotency key is required for payment processing');
  }

  const payload = {
    amount: amountInCents,
    currency: currency.toLowerCase(),
    source: sourceToken,
    description: orderNumber ? `Hisna Gifts Order: ${orderNumber}` : 'Hisna Gifts Purchase',
  };

  const headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${accessToken}`,
    'idempotency-key': idempotencyKey,
  };

  if (clientIp) {
    headers['x-forwarded-for'] = clientIp;
  }

  try {
    logger.info(`Sending Clover charge request. Amount: ${amountInCents} ${currency}, IdempotencyKey: ${idempotencyKey}`);

    const response = await fetch(`${baseUrl}/v1/charges`, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(25000), // 25s timeout
    });

    const data = await response.json().catch(() => ({}));

    if (!response.ok) {
      logger.error('❌ Clover charge error response:', data);
      const errorMessage =
        data?.message ||
        data?.error?.message ||
        data?.error ||
        `Clover payment processing failed (${response.status})`;

      if (response.status === 401 || response.status === 403) {
        throw ApiError.internal('Payment gateway authentication failed. Please verify CLOVER_ACCESS_TOKEN.');
      }

      if (response.status === 402 || response.status === 400) {
        throw ApiError.badRequest(errorMessage);
      }

      throw ApiError.internal(errorMessage);
    }

    logger.info(`✅ Clover charge successful. Charge ID: ${data.id}, Status: ${data.status || 'paid'}`);
    return data;
  } catch (error) {
    if (error instanceof ApiError) {
      throw error;
    }

    logger.error('❌ Clover charge exception:', error.message);

    if (error.name === 'TimeoutError') {
      throw ApiError.internal('Payment gateway timed out. Please retry or check your orders.');
    }

    throw ApiError.internal(error.message || 'Payment processing failed due to network error');
  }
};

/**
 * Refund a charge on Clover (Admin operation)
 *
 * @param {string} chargeId - Clover Charge ID (e.g., ch_...)
 * @param {number} [amountInCents] - Optional partial refund amount
 * @param {string} [idempotencyKey] - Unique key for refund attempt
 */
const refundCharge = async ({ chargeId, amountInCents, idempotencyKey }) => {
  const accessToken = getCloverAccessToken();
  const baseUrl = getCloverBaseUrl();

  const payload = {
    charge: chargeId,
  };
  if (amountInCents) {
    payload.amount = amountInCents;
  }

  const headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${accessToken}`,
  };
  if (idempotencyKey) {
    headers['idempotency-key'] = idempotencyKey;
  }

  try {
    const response = await fetch(`${baseUrl}/v1/refunds`, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(20000),
    });

    const data = await response.json().catch(() => ({}));

    if (!response.ok) {
      logger.error('❌ Clover refund error:', data);
      const message = data?.message || 'Refund failed';
      throw ApiError.badRequest(message);
    }

    return data;
  } catch (error) {
    if (error instanceof ApiError) {
      throw error;
    }
    logger.error('❌ Clover refund exception:', error.message);
    throw ApiError.badRequest(error.message || 'Refund failed');
  }
};

module.exports = {
  createCharge,
  refundCharge,
  getCloverBaseUrl,
};
