const prisma = require('../config/db');
const ApiError = require('../utils/apiError');
const logger = require('../config/logger');
const cloverService = require('./clover.service');

/**
 * Process Clover card charge for an order with idempotency & double-charge safeguards
 *
 * @param {Object} params
 * @param {string} params.orderId - Unique order ID in database
 * @param {string} params.cloverToken - Single-use token generated by clover.js (clv_...)
 * @param {string|null} params.userId - Authenticated user ID (or null for guest)
 * @param {string} [params.clientIp] - Client IP for Clover anti-fraud
 */
const processCloverPayment = async ({ orderId, cloverToken, userId, clientIp }) => {
  if (!orderId) {
    throw ApiError.badRequest('Order ID is required');
  }

  if (!cloverToken) {
    throw ApiError.badRequest('Clover payment token is required');
  }

  const order = await prisma.order.findUnique({
    where: { id: orderId },
    include: { items: true, address: true },
  });

  if (!order) {
    throw ApiError.notFound('Order not found');
  }

  // 1. Authorize user (if order belongs to a specific user)
  if (order.userId && userId && order.userId !== userId) {
    throw ApiError.forbidden('Unauthorized access to this order');
  }

  // 2. Double-charge prevention: If order is already paid, return success immediately without charging again
  if (order.paymentStatus === 'PAID') {
    logger.info(`⚡ Order ${order.orderNumber} is already marked as PAID. Returning existing order.`);
    return {
      success: true,
      alreadyPaid: true,
      order,
      message: 'This order has already been paid successfully.',
    };
  }

  // 3. If a Clover charge was already recorded for this order
  if (order.cloverChargeId) {
    logger.info(`⚡ Order ${order.orderNumber} already has Clover charge ID ${order.cloverChargeId}. Returning order.`);
    return {
      success: true,
      alreadyPaid: true,
      order,
      message: 'Payment for this order has already been processed.',
    };
  }

  // 4. Amount in cents (CAD)
  const amountInCents = Math.round(Number(order.totalAmount) * 100);

  if (amountInCents <= 0) {
    throw ApiError.badRequest('Invalid order total amount');
  }

  // 5. Unique, deterministic idempotency key for this order
  const idempotencyKey = `charge_${order.id}`;

  try {
    // 6. Execute charge on Clover
    const charge = await cloverService.createCharge({
      amountInCents,
      currency: process.env.PAYMENT_CURRENCY || 'cad',
      sourceToken: cloverToken,
      idempotencyKey,
      orderNumber: order.orderNumber,
      clientIp,
    });

    // 7. Update order status to PAID and CONFIRMED
    const updatedOrder = await prisma.order.update({
      where: { id: orderId },
      data: {
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        paymentMethod: 'CLOVER',
        cloverChargeId: charge.id,
        cloverToken: cloverToken,
      },
      include: {
        items: true,
        address: true,
      },
    });

    logger.info(`🎉 Order ${order.orderNumber} marked as PAID via Clover charge ${charge.id}`);

    return {
      success: true,
      order: updatedOrder,
      charge,
    };
  } catch (error) {
    logger.error(`❌ Payment processing failed for order ${order.orderNumber}:`, error.message);

    // If charge definitely failed, mark paymentStatus as FAILED if not already paid
    try {
      await prisma.order.update({
        where: { id: orderId },
        data: { paymentStatus: 'FAILED' },
      });
    } catch (dbErr) {
      logger.error('Failed to update order status to FAILED:', dbErr);
    }

    throw error;
  }
};

/**
 * Handle optional Clover webhook notifications
 */
const handleWebhook = async (payload) => {
  logger.info('Received Clover webhook notification:', JSON.stringify(payload));
  // Process any asynchronous status updates if configured
  return { received: true };
};

module.exports = {
  processCloverPayment,
  handleWebhook,
};
